/*
 * DO NOT EDIT.  THIS FILE IS GENERATED FROM
 * /builds/slave/mozilla-1.9.2-linux-xulrunner/build/dom/interfaces/events/nsIDOMPaintRequest.idl
 */

package org.mozilla.interfaces;

/**
 * These objects are exposed by the MozDOMAfterPaint event. Each one represents
 * a request to repaint a rectangle that was generated by the browser.
 */
public interface nsIDOMPaintRequest extends nsISupports {

  String NS_IDOMPAINTREQUEST_IID =
    "{4802360b-f1c0-4d84-bb9e-9d2ccb9de461}";

  /**
   * The client rect where invalidation was triggered.
   */
  nsIDOMClientRect getClientRect();

  /**
   * The reason for the request, as a string. If an empty string, then we don't know
   * the reason (this is common). Reasons include "scroll repaint", meaning that we
   * needed to repaint the rectangle due to scrolling, and "scroll copy", meaning
   * that we updated the rectangle due to scrolling but instead of painting
   * manually, we were able to do a copy from another area of the screen.
   */
  String getReason();

}